apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello-svc
spec:
  ports:
  - port: 5000
    nodePort: 30080
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello
  type: NodePort
